---
title: "Comparing the doublet detection tools"
author: "Pierre-Luc Germain"
date: "2019/05/23"
output:
  html_document:
    toc: true
    theme: 'cerulean'
    highlight: 'tango'
    code_folding: hide
    keep_md: yes
---

```{r}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(scran)
  library(scDblFinder)
  library(DoubletFinder)
  library(scds)
  library(Seurat)
  library(ROCit)
})

scranWrapper <- function(sce){
  sce$scran.score <- scran::doubletCells(counts(sce)[order(Matrix::rowMeans(counts(sce)), decreasing=TRUE)[1:3000],])
  sce
}
```

# The datasets

```{r}
lf <- list( 
  mixology10x3cl="pipComp/datasets/mixology10x3cl.SCE.rds",
  mixology10x5cl="pipComp/datasets/mixology10x5cl.SCE.rds",
  demuxlet="../Shared_taupo/plger/demuxlet_GSM2560248.SCE.reduced.noAmbiguous.rds"
)
datasets <- lapply(lf, readRDS)

dblProp <- lapply(datasets, FUN=function(x) sum(x$demuxlet_cls=="DBL")/ncol(x))
```

# Running the methods

```{r}
t.elapsed <- matrix(0,nrow=4,ncol=length(datasets), dimnames=list( 
  c("scds", "scran", "scDblFinder", "DoubletFinder"), names(datasets) ))
```

## scDblFinder

```{r}
mname <- "scDblFinder"
for(x in names(datasets)){
  st <- system.time( datasets[[x]] <- scDblFinder(datasets[[x]]) )
  t.elapsed[mname,x] <- st[[3]]
}
```

## scran

```{r}
mname <- "scran"
for(x in names(datasets)){
  st <- system.time( datasets[[x]] <- scranWrapper(datasets[[x]]) )
  t.elapsed[mname,x] <- st[[3]]
}
```

## scds

```{r}
mname <- "scds"
for(x in names(datasets)){
  st <- system.time( datasets[[x]] <- scdsWrapper(datasets[[x]]) )
  t.elapsed[mname,x] <- st[[3]]
}
```

## DoubletFinder

```{r, warning=FALSE, results='hide',message=FALSE}
mname <- "DoubletFinder"
for(x in names(datasets)){
  st <- tryCatch({
    system.time( datasets[[x]] <- dblFinderWrapper(datasets[[x]], dblProp[[x]]) )
  }, error=function(x){ 
    warning(x)
    rep(NA_real_,3)
  })
  t.elapsed[mname,x] <- st[[3]]
}
```

```{r}
for(d in names(lf)){
  saveRDS(datasets[[d]], file=lf[[d]])
}
saveRDS(t.elapsed, file="doublet_running_times.rds")
sessionInfo()
```


# Running time

```{r}
t.elapsed
barplot(t(t.elapsed), ylab="Running time (elapsed), in seconds", beside=TRUE)
```

# Accuracy

```{r}
scoresNames <- c("scran.score"="scran", "scDblFinder.ratio"="scDblFinder", "DF.score"="DoubletFinder", "hybrid_score"="scds")
```

## Mixology10x3cl

```{r}
i <- 1
scores <- colData(datasets[[i]])[,intersect(names(scoresNames),colnames(colData(datasets[[i]])))]
colnames(scores) <- scoresNames[colnames(scores)]
plotROCs(scores, factor(datasets[[i]]$demuxlet_cls, c("SNG","DBL")))
```

## Mixology10x5cl

```{r}
i <- 2
scores <- colData(datasets[[i]])[,intersect(names(scoresNames),colnames(colData(datasets[[i]])))]
colnames(scores) <- scoresNames[colnames(scores)]
plotROCs(scores, factor(datasets[[i]]$demuxlet_cls, c("SNG","DBL")))
```

## Dataset from the Demuxlet paper

```{r}
i <- 3
scores <- colData(datasets[[i]])[,intersect(names(scoresNames),colnames(colData(datasets[[i]])))]
colnames(scores) <- scoresNames[colnames(scores)]
plotROCs(scores, factor(datasets[[i]]$multiplets, c("singlet","doublet")))
```

```{r}
sessionInfo()
```
